### ISSUE TITLE
How to setup SMSC? 

### ISSUE THREAD

**Issue by sheshankkodam** [go-gsm/ucp#1]
In the demo, how did you set up the following config? Is there a way to get these variables from a phone? 

```
Addr:       SMSC_ADDR,
User:       SMSC_USER,
Password:   SMSC_PASSWORD,
AccessCode: SMSC_ACCESSCODE,
```

**Comment by jcaberio** [comment]
Sorry for the late response. These variables are not from the phone but from the [SMSC](https://en.wikipedia.org/wiki/Short_Message_service_center) i.e. the telco network. 
If you want to simulate the SMSC, you can use this [simulator](https://github.com/jcaberio/ucp-smsc-sim). For more details please read this [article](https://blog.gopheracademy.com/advent-2018/how-to-send-and-receive-sms/).
